[supervisord]
nodaemon=true

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock   ; or tcp://127.0.0.1:9001

[program:mariadb]
command=/usr/bin/mysqld --datadir=/var/lib/mysql --user=mysql
autostart=true
autorestart=true
stdout_logfile=/var/log/mariadb.log
stderr_logfile=/var/log/mariadb.err.log
priority=1

[program:initdb]
command=/app/docker/init-db.sh
autostart=true
autorestart=false
priority=2
stdout_logfile=/var/log/initdb.log
stderr_logfile=/var/log/initdb.err.log
startretries=5

[program:springboot]
command=java -jar /app/app.jar
autostart=true
autorestart=true
priority=3
stdout_logfile=/var/log/springboot.log
stderr_logfile=/var/log/springboot.err.log
startsecs=1
