[supervisord]
nodaemon=true
user=root

[program:mariadb]
command=/usr/bin/mysqld --datadir=/var/lib/mysql --user=mysql
autostart=true
autorestart=true
stdout_logfile=/var/log/mariadb.log
stderr_logfile=/var/log/mariadb.err.log

[program:init-db]
command=/app/docker/init-db.sh
user=root
autostart=true
autorestart=false
stdout_logfile=/var/log/initdb.log
stderr_logfile=/var/log/initdb.err.log

[program:campuscart]
command=java -jar /app/app.jar
user=springuser
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
